#!/usr/bin/env python3
"""Generates missing_art_manifest.csv/.json for the JebbyJump art audit.

Single source of truth for the gap rows; every value is evidence-derived
(see per-asset briefs). BLOCKED values are stated, never guessed.
"""
import csv, json, os

OUT = os.path.join(os.path.dirname(__file__), "..", "manifests")

FIELDS = ["asset_id","title","launch_scope","priority","category","subcategory",
"current_status","problem_type","evidence_labels","evidence","used_by_scenes",
"used_by_prefabs","used_by_scripts","used_by_gameobjects","current_asset_path",
"replacement_type","target_asset_path","target_filename","archive_path",
"preserve_existing_meta","existing_meta_path","existing_guid","dependency_count",
"artifact_format","editable_source_format","runtime_width_px","runtime_height_px",
"master_width_px","master_height_px","sprite_mode","frame_count","frame_width_px",
"frame_height_px","frame_layout","pixels_per_unit","pivot_normalized_x",
"pivot_normalized_y","pivot_pixels_x","pivot_pixels_y","content_bounds_px",
"transparent_padding_px","alpha_requirement","colour_space","bit_depth",
"mesh_type","sprite_border_px","filter_mode","wrap_mode","mipmaps","compression",
"max_texture_size","platform_overrides","atlas_group","world_size",
"sorting_layer","order_in_layer","canvas_path","canvas_reference_resolution",
"recttransform_size","anchors","ui_pivot","anchored_position","image_type",
"minimum_touch_target","safe_area_rule","palette_hex","gradient_spec",
"outline_spec","shadow_spec","corner_radius_px","animation_states","fps",
"loop_rule","facing_direction","flipx_safe","reference_asset_paths",
"reference_screenshot_paths","generation_feasibility","requires_reference_image",
"requires_postprocess","requires_human_review","requires_unity_wiring",
"unity_wiring_steps","generation_prompt_path","negative_prompt_path",
"acceptance_criteria","licence_requirement","source_file_requirement",
"confidence","blocker","notes"]

REFS = "Assets/_JebbyJump/Docs/Art/References/jebby_color_knight_character_sheet_v01.png;Assets/_JebbyJump/Docs/Art/References/jebby_outfit_variations_board_v01.png"
STYLE_SHOTS = "ProductionArtAudit/evidence/screenshots/Game__PlayingHUD__1686x948__none__level1-timer-running.png"
PALETTE_CORE = "#E63838;#3878E6;#38BF59;#FAD12E;#9938E6;#F28C26"

def row(**kw):
    r = {k: "" for k in FIELDS}
    r.update(kw)
    return r

ROWS = [
row(asset_id="ART-001", title="Google Play listing app icon", launch_scope="LAUNCH_REQUIRED",
    priority="P0", category="commercial", subcategory="store icon",
    current_status="MISSING (no store assets exist; P31 checklist blocked)",
    problem_type="MISSING;COMMERCIAL_STORE_ASSET",
    evidence_labels="EXTERNAL-SPEC-VERIFIED;STATIC-INSPECTED",
    evidence="support.google.com/googleplay/android-developer/answer/9866151 (fetched 2026-07-14): 512x512 32-bit PNG WITH alpha, max 1024KB; no StoreAssets/ dir exists",
    replacement_type="MARKETING_ONLY", target_asset_path="StoreAssets/Icons/",
    target_filename="jebby_jump_icon_512.png", archive_path="StoreAssets/Icons/jebby_jump_icon_512.png",
    preserve_existing_meta="n/a (outside Assets/)", artifact_format="PNG",
    editable_source_format="layered source recommended (PSD/Affinity)",
    runtime_width_px=512, runtime_height_px=512, master_width_px=1024, master_height_px=1024,
    alpha_requirement="RGBA (Play accepts alpha; Play masks corners itself)",
    colour_space="sRGB", bit_depth=32,
    palette_hex=PALETTE_CORE + ";warm sky pastels", corner_radius_px="none baked (Play applies mask)",
    reference_asset_paths=REFS, reference_screenshot_paths=STYLE_SHOTS,
    generation_feasibility="AI_REFERENCE_GUIDED", requires_reference_image="yes",
    requires_postprocess="yes (exact 512 resize + <=1024KB)", requires_human_review="yes (brand)",
    requires_unity_wiring="no", generation_prompt_path="ProductionArtAudit/asset_briefs/ART-001.md",
    negative_prompt_path="ProductionArtAudit/asset_briefs/ART-001.md#19",
    acceptance_criteria="512x512 RGBA sRGB <=1024KB; Jebby face identity per locked sheet; readable at 48px",
    licence_requirement="provenance record required", source_file_requirement="master 1024 kept",
    confidence="high"),
row(asset_id="ART-002", title="Android adaptive icon foreground", launch_scope="LAUNCH_REQUIRED",
    priority="P0", category="commercial", subcategory="launcher icon layer",
    current_status="MISSING (all PlayerSettings icon slots m_Textures:[] - IMPORT-VERIFIED)",
    problem_type="MISSING;COMMERCIAL_STORE_ASSET",
    evidence_labels="EXTERNAL-SPEC-VERIFIED;IMPORT-VERIFIED",
    evidence="developer.android.com adaptive icons (fetched 2026-07-14): layers 108x108dp, inner 66dp safe zone, outer 18dp masked; ProjectSettings.asset icon arrays empty",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Icons/", target_filename="ic_launcher_foreground_432.png",
    archive_path="Assets/_JebbyJump/Art/Icons/ic_launcher_foreground_432.png",
    preserve_existing_meta="new file - Unity will create .meta on import",
    artifact_format="PNG", runtime_width_px=432, runtime_height_px=432,
    master_width_px=864, master_height_px=864,
    alpha_requirement="RGBA transparent outside subject",
    colour_space="sRGB", bit_depth=32,
    content_bounds_px="subject within centre 264x264 (66dp safe zone @4x); nothing critical outside",
    transparent_padding_px=">=72px each side fully maskable (18dp @4x)",
    palette_hex=PALETTE_CORE, reference_asset_paths=REFS,
    generation_feasibility="AI_PLUS_DETERMINISTIC_POSTPROCESS", requires_reference_image="yes",
    requires_postprocess="yes (safe-zone bounds check + exact canvas)", requires_human_review="yes",
    requires_unity_wiring="yes",
    unity_wiring_steps="PlayerSettings > Android > Adaptive icon foreground slot (or extend Apply Approved Build Config); rebuild AAB; re-run preflight",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-002.md",
    acceptance_criteria="432x432 RGBA; Jebby head/badge inside 264px centre circle; survives circle+squircle masks",
    licence_requirement="provenance record required", source_file_requirement="master kept",
    confidence="high"),
row(asset_id="ART-003", title="Android adaptive icon background", launch_scope="LAUNCH_REQUIRED",
    priority="P0", category="commercial", subcategory="launcher icon layer",
    current_status="MISSING", problem_type="MISSING;COMMERCIAL_STORE_ASSET",
    evidence_labels="EXTERNAL-SPEC-VERIFIED;IMPORT-VERIFIED",
    evidence="same as ART-002; background layer required",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Icons/", target_filename="ic_launcher_background_432.png",
    archive_path="Assets/_JebbyJump/Art/Icons/ic_launcher_background_432.png",
    preserve_existing_meta="new file", artifact_format="PNG",
    runtime_width_px=432, runtime_height_px=432, master_width_px=864, master_height_px=864,
    alpha_requirement="fully opaque", colour_space="sRGB", bit_depth=24,
    palette_hex="soft sky gradient sampled from bg_sky_layer_01.png pastels",
    gradient_spec="vertical soft pastel (top lighter), edge-to-edge, no focal detail (18dp margins masked/parallaxed)",
    reference_asset_paths="Assets/_JebbyJump/Art/Sprites/Backgrounds/bg_sky_layer_01.png",
    generation_feasibility="AI_DIRECT", requires_reference_image="yes",
    requires_postprocess="yes (exact canvas, strip alpha)", requires_human_review="no",
    requires_unity_wiring="yes", unity_wiring_steps="PlayerSettings adaptive background slot; rebuild",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-003.md",
    acceptance_criteria="432x432 opaque; no detail that breaks when masked/panned",
    licence_requirement="provenance record", source_file_requirement="master kept", confidence="high"),
row(asset_id="ART-004", title="Play feature graphic", launch_scope="LAUNCH_REQUIRED",
    priority="P0", category="commercial", subcategory="store graphic",
    current_status="MISSING (P31 blocked item)", problem_type="MISSING;COMMERCIAL_STORE_ASSET",
    evidence_labels="EXTERNAL-SPEC-VERIFIED",
    evidence="Play listing spec (fetched 2026-07-14): 1024x500 JPEG or 24-bit PNG, NO alpha",
    replacement_type="MARKETING_ONLY", target_asset_path="StoreAssets/Feature/",
    target_filename="jebby_jump_feature_1024x500.png",
    archive_path="StoreAssets/Feature/jebby_jump_feature_1024x500.png",
    preserve_existing_meta="n/a", artifact_format="PNG (24-bit, no alpha)",
    runtime_width_px=1024, runtime_height_px=500, master_width_px=2048, master_height_px=1000,
    alpha_requirement="NO alpha (opaque)", colour_space="sRGB", bit_depth=24,
    safe_area_rule="keep wordmark/subject in centre ~80% (edges may crop in some Play placements)",
    palette_hex=PALETTE_CORE + ";pastel sky", reference_asset_paths=REFS,
    reference_screenshot_paths=STYLE_SHOTS,
    generation_feasibility="AI_REFERENCE_GUIDED", requires_reference_image="yes",
    requires_postprocess="yes (exact canvas, alpha strip)", requires_human_review="yes (brand)",
    requires_unity_wiring="no", generation_prompt_path="ProductionArtAudit/asset_briefs/ART-004.md",
    acceptance_criteria="1024x500 opaque; Jebby identity; no baked UI/claims text; wordmark optional (needs ART-010 first)",
    licence_requirement="provenance record", source_file_requirement="master kept", confidence="high"),
row(asset_id="ART-005", title="Gameplay floor/start strip sprite", launch_scope="LAUNCH_REQUIRED",
    priority="P1", category="platform", subcategory="ground strip",
    current_status="PLACEHOLDER IN PRODUCTION: Floor renders Placeholder.png 32x32 tinted #F2EBD9, scaled 37.64x0.5",
    problem_type="PLACEHOLDER_REPLACEMENT",
    evidence_labels="DEPENDENCY-VERIFIED;RUNTIME-OBSERVED;FILE-MEASURED",
    evidence="Game.unity Floor SpriteRenderer sprite guid d0440e8857eb55c45bdf8508fee4ebdd = Placeholder.png; visible cream band in review screenshots",
    used_by_scenes="Game.unity", used_by_gameobjects="Floor",
    current_asset_path="Assets/_JebbyJump/Art/Sprites/Placeholder.png",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Sprites/Platforms/",
    target_filename="spr_floor_strip_01.png",
    archive_path="Assets/_JebbyJump/Art/Sprites/Platforms/spr_floor_strip_01.png",
    preserve_existing_meta="new file", artifact_format="PNG",
    runtime_width_px=512, runtime_height_px=128, master_width_px=1024, master_height_px=256,
    sprite_mode="Single", pixels_per_unit=100,
    pivot_normalized_x=0.5, pivot_normalized_y=1.0,
    alpha_requirement="RGBA (soft top edge OK); tileable horizontally",
    colour_space="sRGB", bit_depth=32, wrap_mode="Repeat (drawMode Tiled)",
    world_size="~37.6 world units wide; DECIDED (D1, 2026-07-16): taller cloud-meadow ledge, ~0.6 world-unit visible ground (512x128 art, drawMode Tiled)",
    palette_hex="#F2EBD9 cream base (current tint) + soft pastel grass/cloud accent",
    reference_asset_paths="Assets/_JebbyJump/Art/Sprites/Backgrounds/bg_sky_layer_01.png",
    reference_screenshot_paths=STYLE_SHOTS,
    generation_feasibility="AI_PLUS_DETERMINISTIC_POSTPROCESS", requires_reference_image="yes",
    requires_postprocess="yes (seamless-tile check)", requires_human_review="no",
    requires_unity_wiring="yes",
    unity_wiring_steps="assign to Floor SpriteRenderer (drawMode Tiled recommended); reset tint to white; adjust scale; keep collider unchanged; then delete Placeholder.png",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-005.md",
    acceptance_criteria="tiles seamlessly on X; reads as ground vs sky; doesn't fight platform colours",
    licence_requirement="provenance record", source_file_requirement="master kept",
    blocker="", confidence="high"),
row(asset_id="ART-006", title="Main-menu background", launch_scope="LAUNCH_REQUIRED",
    priority="P1", category="background", subcategory="menu",
    current_status="MISSING (flat navy camera clear colour)", problem_type="MISSING",
    evidence_labels="RUNTIME-OBSERVED;LIVE-INSPECTED",
    evidence="review screenshot MainMenu__MainMenu__...png: flat blue; no background object in hierarchy",
    used_by_scenes="MainMenu.unity",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Sprites/Backgrounds/",
    target_filename="bg_menu_01.png", archive_path="Assets/_JebbyJump/Art/Sprites/Backgrounds/bg_menu_01.png",
    preserve_existing_meta="new file", artifact_format="PNG",
    runtime_width_px=2400, runtime_height_px=1080, master_width_px=2400, master_height_px=1080,
    alpha_requirement="opaque", colour_space="sRGB", bit_depth=24,
    canvas_path="MainMenuCanvas (Screen Space Overlay, ref 1920x1080)",
    canvas_reference_resolution="1920x1080", image_type="Simple, preserveAspect envelope-fill",
    safe_area_rule="20:9 coverage (2400 wide) so 16:9..20:9 crop safely; keep focal art centre-right (menu stack centre)",
    palette_hex="pastel sky family of bg_sky_layer_01",
    reference_asset_paths="Assets/_JebbyJump/Art/Sprites/Backgrounds/bg_sky_layer_01.png;" + REFS,
    generation_feasibility="AI_REFERENCE_GUIDED", requires_reference_image="yes",
    requires_postprocess="yes (exact canvas)", requires_human_review="no",
    requires_unity_wiring="yes",
    unity_wiring_steps="add full-screen Image behind TitleText in MainMenuCanvas (first sibling); assign sprite; envelope scaling",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-006.md",
    acceptance_criteria="menu text readable on top (contrast); style-matched to gameplay sky",
    licence_requirement="provenance record", source_file_requirement="master kept", confidence="high"),
row(asset_id="ART-007", title="Shell UI panel (9-slice)", launch_scope="LAUNCH_REQUIRED",
    priority="P1", category="ui", subcategory="panel/card chrome",
    current_status="PLACEHOLDER: all shell panels/cards use Unity built-in UISprite tinted (0.15,0.15,0.2)",
    problem_type="PLACEHOLDER_REPLACEMENT",
    evidence_labels="STATIC-INSPECTED;RUNTIME-OBSERVED",
    evidence="scaffold sources (BuildGameShellCanvas.cs:132 etc.) tint built-in sprite; flat rects in all review shots",
    used_by_scenes="MainMenu.unity;Game.unity",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Sprites/UI/",
    target_filename="ui_panel_soft_9s.png", archive_path="Assets/_JebbyJump/Art/Sprites/UI/ui_panel_soft_9s.png",
    preserve_existing_meta="new file", artifact_format="PNG",
    runtime_width_px=256, runtime_height_px=256, master_width_px=512, master_height_px=512,
    sprite_mode="Single (9-sliced)", pixels_per_unit=100,
    sprite_border_px="BLOCKED - derive from generated corner radius; candidate 64px all sides on 256 canvas",
    corner_radius_px="candidate 48 (OPEN_SCOPE_DECISION - no approved radius system exists)",
    alpha_requirement="RGBA (soft outer shadow optional)", colour_space="sRGB", bit_depth=32,
    image_type="Sliced", palette_hex="deep neutral #262633 body + light border, per Art Bible rounded/soft",
    reference_asset_paths="Assets/_JebbyJump/Art/Sprites/UI/ui_btn_jump.png (style anchor);" + REFS,
    generation_feasibility="VECTOR_OR_CODE_GENERATION_PREFERRED", requires_reference_image="yes",
    requires_postprocess="yes (uniform corners; stretch-region flatness check)", requires_human_review="no",
    requires_unity_wiring="yes",
    unity_wiring_steps="set 9-slice borders in Sprite Editor; swap Image sprites on panels/cards (scene edit, multiple objects); keep tint white",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-007.md",
    acceptance_criteria="stretch regions perfectly flat; corners identical; readable text contrast",
    licence_requirement="n/a shape", source_file_requirement="vector source preferred",
    blocker="corner-radius system = OPEN_SCOPE_DECISION", confidence="medium"),
row(asset_id="ART-008", title="Shell UI pill button (9-slice)", launch_scope="LAUNCH_REQUIRED",
    priority="P1", category="ui", subcategory="button chrome",
    current_status="PLACEHOLDER: built-in UISprite tinted (0.2,0.2,0.25)", problem_type="PLACEHOLDER_REPLACEMENT",
    evidence_labels="STATIC-INSPECTED;RUNTIME-OBSERVED",
    evidence="scaffold tints; flat rect buttons in all shell screenshots; Art Bible requires pill-style",
    used_by_scenes="MainMenu.unity;Game.unity",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Sprites/UI/",
    target_filename="ui_btn_pill_9s.png", archive_path="Assets/_JebbyJump/Art/Sprites/UI/ui_btn_pill_9s.png",
    preserve_existing_meta="new file", artifact_format="PNG",
    runtime_width_px=256, runtime_height_px=96, master_width_px=512, master_height_px=192,
    sprite_mode="Single (9-sliced)", sprite_border_px="left/right 48 top/bottom 40 on 256x96 (candidate; pill =半 height radius)",
    corner_radius_px="48 (= half of 96 height, true pill)",
    alpha_requirement="RGBA", colour_space="sRGB", bit_depth=32, image_type="Sliced",
    minimum_touch_target="90 canvas units (ShellLayoutMetrics single-source)",
    palette_hex="state via Unity tint (Normal white base art; pressed/disabled tints) - single bitmap",
    reference_asset_paths="Assets/_JebbyJump/Art/Sprites/UI/ui_btn_jump.png;" + REFS,
    generation_feasibility="VECTOR_OR_CODE_GENERATION_PREFERRED", requires_reference_image="yes",
    requires_postprocess="yes", requires_human_review="no", requires_unity_wiring="yes",
    unity_wiring_steps="9-slice borders; swap Button Image sprites across shell; verify tint-based states + focus ring still read",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-008.md",
    acceptance_criteria="pill silhouette; flat stretch centre; >=90u touch preserved",
    licence_requirement="n/a", source_file_requirement="vector preferred", confidence="medium"),
row(asset_id="ART-009", title="Play store screenshots (set of 4+)", launch_scope="LAUNCH_REQUIRED",
    priority="P0", category="commercial", subcategory="store screenshots",
    current_status="MISSING (P31 ScreenshotStatus=CaptureRequired)", problem_type="MISSING;COMMERCIAL_STORE_ASSET",
    evidence_labels="EXTERNAL-SPEC-VERIFIED",
    evidence="Play spec (2026-07-14): min 2, JPEG/24-bit PNG no alpha, 320..3840px, max<=2x min; promo rec: >=4 at 1920x1080 landscape",
    replacement_type="MARKETING_ONLY", target_asset_path="StoreAssets/Screenshots/",
    target_filename="shot_01_gameplay.png .. shot_04_wardrobe.png",
    archive_path="StoreAssets/Screenshots/",
    artifact_format="PNG 24-bit no alpha", runtime_width_px=1920, runtime_height_px=1080,
    alpha_requirement="NO alpha", colour_space="sRGB", bit_depth=24,
    generation_feasibility="HUMAN_ARTIST_REQUIRED", requires_reference_image="n/a",
    requires_postprocess="optional caption frames only", requires_human_review="yes",
    requires_unity_wiring="no",
    unity_wiring_steps="none - REAL captures from the game (never AI-fabricated gameplay; Play policy + honesty)",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-009.md",
    acceptance_criteria="real gameplay/wardrobe/menu frames at 1920x1080 AFTER ART-005..008 land; truthful",
    licence_requirement="own captures", source_file_requirement="raw captures kept",
    blocker="capture after UI kit lands; needs focused editor or device", confidence="high"),
row(asset_id="ART-010", title="Jebby Jump wordmark / logo", launch_scope="LAUNCH_REQUIRED",
    priority="P1", category="brand", subcategory="wordmark",
    current_status="MISSING (title = plain LiberationSans TMP text)", problem_type="MISSING",
    evidence_labels="RUNTIME-OBSERVED;STATIC-INSPECTED",
    evidence="MainMenu TitleText is TMP with default font; store listing + feature graphic + splash all want a mark",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Sprites/UI/", target_filename="ui_wordmark_jebbyjump.png",
    archive_path="Assets/_JebbyJump/Art/Sprites/UI/ui_wordmark_jebbyjump.png",
    preserve_existing_meta="new file", artifact_format="PNG (+ SVG master required)",
    editable_source_format="SVG/vector REQUIRED",
    runtime_width_px=1200, runtime_height_px=400, master_width_px=2400, master_height_px=800,
    alpha_requirement="RGBA", colour_space="sRGB", bit_depth=32,
    palette_hex="rainbow-gem accent on warm letters; must pass on pastel sky AND dark panel",
    reference_asset_paths=REFS,
    generation_feasibility="LEGAL_OR_BRAND_REVIEW_REQUIRED", requires_reference_image="yes",
    requires_postprocess="yes", requires_human_review="yes (brand+legal: lettering originality, trademark search)",
    requires_unity_wiring="yes",
    unity_wiring_steps="replace TitleText TMP with Image (or add above); optional Unity splash logo slot; store reuse",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-010.md",
    acceptance_criteria="readable at 200px wide; child-friendly rounded letterforms; vector master delivered",
    licence_requirement="original lettering or licensed display font (record it)",
    source_file_requirement="SVG master REQUIRED",
    blocker="brand/legal review before store use", confidence="medium"),
row(asset_id="ART-011", title="Bubble Shield skill icon", launch_scope="LAUNCH_RECOMMENDED",
    priority="P2", category="item/skill", subcategory="HUD skill icon",
    current_status="MISSING - Skill2Icon reuses ui_btn_bg.png (generic circle)",
    problem_type="MISSING;INCOMPLETE_STATE_SET",
    evidence_labels="DEPENDENCY-VERIFIED;RUNTIME-OBSERVED",
    evidence="Game.unity Skill2Icon m_Sprite -> ui_btn_bg guid; plain orb in HUD screenshots",
    used_by_scenes="Game.unity", used_by_gameobjects="Btn_Skill2/Skill2Icon",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Sprites/UI/", target_filename="ui_icon_skill_shield_01.png",
    archive_path="Assets/_JebbyJump/Art/Sprites/UI/ui_icon_skill_shield_01.png",
    artifact_format="PNG", runtime_width_px=256, runtime_height_px=256,
    master_width_px=512, master_height_px=512, pixels_per_unit=100,
    pivot_normalized_x=0.5, pivot_normalized_y=0.5,
    alpha_requirement="RGBA, transparent corners", colour_space="sRGB", bit_depth=32,
    recttransform_size="~70x70 canvas units inside 100u button (match RocketBootsIcon layout)",
    palette_hex="aqua/blue bubble on gold-trim style of existing controls",
    reference_asset_paths="Assets/_JebbyJump/Art/Sprites/UI/ui_btn_jump.png;Assets/_JebbyJump/Art/Sprites/Items/spr_item_rocket_boots_01.png",
    generation_feasibility="AI_REFERENCE_GUIDED", requires_reference_image="yes",
    requires_postprocess="yes", requires_human_review="no", requires_unity_wiring="yes",
    unity_wiring_steps="assign to Skill2Icon Image in Game.unity",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-011.md",
    acceptance_criteria="reads as shield/bubble at 70px; style-matched to rocket boots icon",
    licence_requirement="provenance record", source_file_requirement="master kept", confidence="high"),
row(asset_id="ART-012", title="Health Potion skill icon", launch_scope="LAUNCH_RECOMMENDED",
    priority="P2", category="item/skill", subcategory="HUD skill icon",
    current_status="MISSING - Skill3Icon reuses ui_btn_bg.png", problem_type="MISSING",
    evidence_labels="DEPENDENCY-VERIFIED;RUNTIME-OBSERVED",
    evidence="Game.unity Skill3Icon m_Sprite -> ui_btn_bg guid",
    used_by_scenes="Game.unity", used_by_gameobjects="Btn_Skill3/Skill3Icon",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Sprites/UI/", target_filename="ui_icon_skill_potion_01.png",
    archive_path="Assets/_JebbyJump/Art/Sprites/UI/ui_icon_skill_potion_01.png",
    artifact_format="PNG", runtime_width_px=256, runtime_height_px=256,
    master_width_px=512, master_height_px=512,
    alpha_requirement="RGBA transparent corners", colour_space="sRGB", bit_depth=32,
    palette_hex="warm red/pink heart-potion; child-safe (no medical cross)",
    reference_asset_paths="Assets/_JebbyJump/Art/Sprites/UI/ui_icon_life_01.png;Assets/_JebbyJump/Art/Sprites/Items/spr_item_rocket_boots_01.png",
    generation_feasibility="AI_REFERENCE_GUIDED", requires_reference_image="yes",
    requires_postprocess="yes", requires_human_review="no", requires_unity_wiring="yes",
    unity_wiring_steps="assign to Skill3Icon Image in Game.unity",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-012.md",
    acceptance_criteria="reads as potion at 70px; heart motif ties to lives",
    licence_requirement="provenance record", source_file_requirement="master kept", confidence="high"),
row(asset_id="ART-013", title="Bubble shield VFX sprite", launch_scope="LAUNCH_RECOMMENDED",
    priority="P2", category="vfx", subcategory="skill effect",
    current_status="PLACEHOLDER - BubbleShieldEffect renders ui_btn_right.png (an ARROW)",
    problem_type="PLACEHOLDER_REPLACEMENT",
    evidence_labels="DEPENDENCY-VERIFIED",
    evidence="Game.unity BubbleShieldEffect m_Sprite -> ui_btn_right guid",
    used_by_scenes="Game.unity", used_by_gameobjects="BubbleShieldEffect",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Sprites/VFX/", target_filename="fx_bubble_shield_01.png",
    archive_path="Assets/_JebbyJump/Art/Sprites/VFX/fx_bubble_shield_01.png",
    artifact_format="PNG", runtime_width_px=512, runtime_height_px=512, pixels_per_unit=100,
    alpha_requirement="RGBA soft translucent bubble (centre ~30% alpha, rim brighter)",
    colour_space="sRGB", bit_depth=32,
    world_size="~2.6 world units diameter (encircles 1122px/PPU100*~0.23 scale Jebby - verify live at wiring time)",
    palette_hex="#3878E6 family translucent + white rim highlights",
    reference_asset_paths=REFS,
    generation_feasibility="AI_PLUS_DETERMINISTIC_POSTPROCESS", requires_reference_image="no",
    requires_postprocess="yes (radial symmetry/alpha profile)", requires_human_review="no",
    requires_unity_wiring="yes", unity_wiring_steps="assign to BubbleShieldEffect SpriteRenderer; keep tint/animation code unchanged",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-013.md",
    acceptance_criteria="reads as protective bubble over Jebby; not opaque (gameplay visible through)",
    licence_requirement="provenance record", source_file_requirement="master kept", confidence="medium"),
row(asset_id="ART-014", title="Color echo ring VFX sprite", launch_scope="LAUNCH_RECOMMENDED",
    priority="P2", category="vfx", subcategory="skill effect",
    current_status="PLACEHOLDER - ColorEchoEffect renders ui_btn_bg.png", problem_type="PLACEHOLDER_REPLACEMENT",
    evidence_labels="DEPENDENCY-VERIFIED",
    evidence="Game.unity ColorEchoEffect m_Sprite -> ui_btn_bg guid",
    used_by_scenes="Game.unity", used_by_gameobjects="ColorEchoEffect",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Sprites/VFX/", target_filename="fx_color_echo_ring_01.png",
    archive_path="Assets/_JebbyJump/Art/Sprites/VFX/fx_color_echo_ring_01.png",
    artifact_format="PNG", runtime_width_px=512, runtime_height_px=512, pixels_per_unit=100,
    alpha_requirement="RGBA ring (hollow centre) so runtime tint drives the colour",
    colour_space="sRGB", bit_depth=32,
    palette_hex="WHITE/neutral ring art - tinted at runtime to the platform semantic colours",
    generation_feasibility="VECTOR_OR_CODE_GENERATION_PREFERRED", requires_reference_image="no",
    requires_postprocess="yes (perfect circle)", requires_human_review="no",
    requires_unity_wiring="yes", unity_wiring_steps="assign to ColorEchoEffect SpriteRenderer",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-014.md",
    acceptance_criteria="neutral base tints cleanly to all 6 platform colours",
    licence_requirement="n/a", source_file_requirement="vector preferred", confidence="high"),
row(asset_id="ART-015", title="Adaptive icon monochrome layer", launch_scope="LAUNCH_RECOMMENDED",
    priority="P2", category="commercial", subcategory="launcher icon layer",
    current_status="MISSING (optional per Android docs)", problem_type="MISSING;COMMERCIAL_STORE_ASSET",
    evidence_labels="EXTERNAL-SPEC-VERIFIED",
    evidence="Android adaptive icon docs: monochrome optional, recommended for Android 13+ theming",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Icons/", target_filename="ic_launcher_monochrome_432.png",
    archive_path="Assets/_JebbyJump/Art/Icons/ic_launcher_monochrome_432.png",
    artifact_format="PNG", runtime_width_px=432, runtime_height_px=432,
    alpha_requirement="single-colour silhouette on transparency (alpha only)",
    colour_space="sRGB", bit_depth=32,
    content_bounds_px="inside centre 264x264 like ART-002",
    generation_feasibility="AI_PLUS_DETERMINISTIC_POSTPROCESS", requires_reference_image="yes (ART-002 output)",
    requires_postprocess="yes (flatten to single colour + alpha)", requires_human_review="no",
    requires_unity_wiring="yes", unity_wiring_steps="Unity Android icon monochrome slot (if exposed) or Gradle template note",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-015.md",
    acceptance_criteria="recognizable Jebby silhouette in one colour", licence_requirement="n/a derived",
    source_file_requirement="derived from ART-002 master", confidence="high"),
row(asset_id="ART-016", title="Marketing key art", launch_scope="LAUNCH_RECOMMENDED",
    priority="P2", category="commercial", subcategory="key art",
    current_status="MISSING", problem_type="MISSING;COMMERCIAL_STORE_ASSET",
    evidence_labels="DOC-REQUIRED",
    evidence="P31 store package + press needs; no marketing art exists anywhere in repo",
    replacement_type="MARKETING_ONLY", target_asset_path="Marketing/KeyArt/",
    target_filename="jebby_jump_keyart_3840x2160.png",
    archive_path="Marketing/KeyArt/jebby_jump_keyart_3840x2160.png",
    artifact_format="PNG", runtime_width_px=3840, runtime_height_px=2160,
    master_width_px=3840, master_height_px=2160,
    alpha_requirement="opaque", colour_space="sRGB", bit_depth=24,
    palette_hex="full locked palette; rainbow-tower motif",
    reference_asset_paths=REFS,
    generation_feasibility="AI_REFERENCE_GUIDED", requires_reference_image="yes",
    requires_postprocess="yes", requires_human_review="yes (brand)", requires_unity_wiring="no",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-016.md",
    acceptance_criteria="Jebby identity exact; reusable crop for feature graphic",
    licence_requirement="provenance record", source_file_requirement="layered master kept", confidence="medium"),
row(asset_id="ART-017", title="Cactus warning/contact variant", launch_scope="LAUNCH_RECOMMENDED",
    priority="P3", category="obstacle", subcategory="hazard state",
    current_status="single static cactus only", problem_type="INCOMPLETE_STATE_SET",
    evidence_labels="STATIC-INSPECTED;DOC-REQUIRED",
    evidence="GDD hazards; spr_cactus_obstacle_01.png sole variant; no anticipation/contact art",
    used_by_scenes="Game.unity (spawned)",
    current_asset_path="Assets/_JebbyJump/Art/Sprites/Obstacles/spr_cactus_obstacle_01.png",
    replacement_type="NEW_ASSET_REQUIRES_WIRING",
    target_asset_path="Assets/_JebbyJump/Art/Sprites/Obstacles/",
    target_filename="spr_cactus_obstacle_warn_01.png",
    archive_path="Assets/_JebbyJump/Art/Sprites/Obstacles/spr_cactus_obstacle_warn_01.png",
    artifact_format="PNG", runtime_width_px=1254, runtime_height_px=1254,
    pixels_per_unit="match existing 1254 (or re-export BOTH to PPU 100 - see integration note)",
    pivot_normalized_x=0.5, pivot_normalized_y=0.0,
    alpha_requirement="RGBA transparent corners", colour_space="sRGB", bit_depth=32,
    reference_asset_paths="Assets/_JebbyJump/Art/Sprites/Obstacles/spr_cactus_obstacle_01.png",
    generation_feasibility="AI_REFERENCE_GUIDED", requires_reference_image="yes",
    requires_postprocess="yes (bounds match base cactus)", requires_human_review="no",
    requires_unity_wiring="yes", unity_wiring_steps="requires code: swap/flash on anticipation (design decision)",
    generation_prompt_path="ProductionArtAudit/asset_briefs/ART-017.md",
    acceptance_criteria="same silhouette+bounds as base; friendly non-scary warning read",
    licence_requirement="provenance record", source_file_requirement="master kept",
    blocker="needs gameplay design decision on anticipation behaviour", confidence="low"),
]

def main():
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "missing_art_manifest.csv"), "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader(); w.writerows(ROWS)
    with open(os.path.join(OUT, "missing_art_manifest.json"), "w", encoding="utf-8") as f:
        json.dump(ROWS, f, indent=1)
    print(f"missing-art manifest: {len(ROWS)} rows")
    print("LAUNCH_REQUIRED:", sum(1 for r in ROWS if r["launch_scope"] == "LAUNCH_REQUIRED"))
    print("LAUNCH_RECOMMENDED:", sum(1 for r in ROWS if r["launch_scope"] == "LAUNCH_RECOMMENDED"))

if __name__ == "__main__":
    main()
